/* Live conversion client
 * Copyright (C) 2017 Red Hat Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef LIVE_H
#define LIVE_H

/* We don't use libguestfs directly here, and we don't link to it
 * either.  However we include this just so that we can use the
 * convenience macros in utils.h.
 */
#include "guestfs.h"
#include "guestfs-utils.h"

/* Ensure we don't use libguestfs. */
#define guestfs_h DO_NOT_USE

/* RPC stuff. */
#include <rpc/xdr.h>
#include "live_protocol.h"       /* generated by rpcgen */
#include "live-protocol-extra.h" /* from generator */

extern int verbose;

/* conversion.c */
extern void do_live_conversion (const char *server, const char *token);

#endif /* LIVE_H */
